version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/postgres-data:/var/lib/postgresql/data
      

  python-flask:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src
    
    
