"""empty message

Revision ID: 24a5b8aaa145
Revises: 32fdc923ec3d
Create Date: 2021-07-09 05:46:22.860072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a5b8aaa145'
down_revision = '32fdc923ec3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_user_public_id_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_user_public_id_key', 'posts', ['user_public_id'])
    # ### end Alembic commands ###
