"""empty message

Revision ID: 32fdc923ec3d
Revises: 196d82312e07
Create Date: 2021-07-09 05:39:02.884982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fdc923ec3d'
down_revision = '196d82312e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_public_id'], ['users.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('posts', 'dislikes')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('likes')
    # ### end Alembic commands ###
