"""empty message

Revision ID: 12dce0ffea7f
Revises: bc1377805122
Create Date: 2021-07-09 12:20:44.021253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dce0ffea7f'
down_revision = 'bc1377805122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('creation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'creation_date')
    # ### end Alembic commands ###
