"""empty message

Revision ID: d7c93f904d53
Revises: 24a5b8aaa145
Create Date: 2021-07-09 07:51:24.760781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c93f904d53'
down_revision = '24a5b8aaa145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'liked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
